import logging
from typing import Dict, Any, Optional, Callable
import yt_dlp

import os
from pathlib import Path
from backend.services.ffmpeg_service import get_ffmpeg_dir

logger = logging.getLogger("mediaflow.extractor")

class ExtractorError(Exception):
    """Custom exception for extraction issues."""
    pass

class MediaRestrictedError(ExtractorError):
    """Exception when media is protected by DRM or access restrictions."""
    pass

def get_ydl_base_options() -> Dict[str, Any]:
    """Returns safe, secure default options for yt-dlp with Windows filesystem resilience and anti-bot bypass."""
    opts: Dict[str, Any] = {
        "quiet": True,
        "no_warnings": True,
        "noplaylist": True,
        "socket_timeout": 25,
        "retries": 3,
        "nocheckcertificate": False,
        "prefer_insecure": False,
        "ignoreerrors": False,
        "geo_bypass": True,
        "extract_flat": False,
        "windowsfilenames": True,
        "restrictfilenames": True,
        "trim_file_name": 100,
        "updatetime": False,       # Prevents Windows os.utime [Errno 22] Invalid argument
        "no_mtime": True,
        "overwrites": True,
        "nopart": True,            # Writes directly to output file, avoiding Windows rename/replace [Errno 22]
        "no_color": True,
        "http_headers": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
            "Accept-Language": "en-US,en;q=0.9",
        },
    }

    # Bind JS Runtime (Node.js or Deno) for YouTube signature deciphering
    import shutil
    if shutil.which("node"):
        opts["js_runtimes"] = {"node": {}}
    elif shutil.which("deno"):
        opts["js_runtimes"] = {"deno": {}}

    # Bind cookies if passed via environment variable (useful for Render/Cloud hosts)
    raw_cookies = (
        os.environ.get("YOUTUBE_COOKIES") or 
        os.environ.get("YOUTUBE_COOKIE") or 
        os.environ.get("COOKIES") or 
        os.environ.get("COOKIE") or 
        os.environ.get("COOKIES_DATA") or
        os.environ.get("COOKIES_TEXT")
    )
    if raw_cookies and raw_cookies.strip():
        import tempfile
        import base64
        data = raw_cookies.strip()
        # Strip wrapping quotes if user pasted with quotes
        if (data.startswith('"') and data.endswith('"')) or (data.startswith("'") and data.endswith("'")):
            data = data[1:-1].strip()
        if "\\n" in data and "\n" not in data:
            data = data.replace("\\n", "\n")
        try:
            if not ("# Netscape" in data or "\t" in data) and len(data) > 30:
                data = base64.b64decode(data).decode("utf-8")
        except Exception:
            pass

        # Normalize space-separated cookie columns into tab-separated Netscape format
        normalized_lines = ["# Netscape HTTP Cookie File", "# Autogenerated by MediaFlow for Render"]
        for line in data.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "\t" in line:
                parts = line.split("\t")
                if len(parts) >= 7:
                    normalized_lines.append("\t".join(parts))
                    continue
            # Browser form paste converts \t to spaces; restore tabs
            parts = line.split()
            if len(parts) >= 7:
                domain = parts[0]
                flag = parts[1]
                path = parts[2]
                secure = parts[3]
                expiration = parts[4]
                name = parts[5]
                value = " ".join(parts[6:])
                normalized_lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}")
        
        cookie_data = "\n".join(normalized_lines) + "\n"
        cookie_path = os.path.join(tempfile.gettempdir(), "mediaflow_yt_cookies.txt")
        try:
            with open(cookie_path, "w", encoding="utf-8") as f:
                f.write(cookie_data)
            opts["cookiefile"] = cookie_path
            logger.info(f"Loaded {len(normalized_lines)-2} cookies ({len(cookie_data)} bytes) into {cookie_path}")
        except Exception as e:
            logger.warning(f"Could not write YOUTUBE_COOKIES to temp file: {e}")
    else:
        cookie_file = os.environ.get("COOKIES_FILE") or os.environ.get("YOUTUBE_COOKIES_FILE")
        if cookie_file and os.path.exists(cookie_file):
            opts["cookiefile"] = cookie_file
        elif os.path.exists("cookies.txt"):
            opts["cookiefile"] = "cookies.txt"

    # Bind proxy if configured
    proxy = (
        os.environ.get("HTTP_PROXY") or 
        os.environ.get("HTTPS_PROXY") or 
        os.environ.get("PROXY") or 
        os.environ.get("YOUTUBE_PROXY")
    )
    if proxy and proxy.strip():
        clean_proxy = proxy.strip()
        if (clean_proxy.startswith('"') and clean_proxy.endswith('"')) or (clean_proxy.startswith("'") and clean_proxy.endswith("'")):
            clean_proxy = clean_proxy[1:-1].strip()
        opts["proxy"] = clean_proxy

    # Bind FFmpeg location if available
    try:
        ffmpeg_dir = get_ffmpeg_dir()
        if ffmpeg_dir:
            opts["ffmpeg_location"] = ffmpeg_dir
    except Exception as e:
        logger.debug(f"Could not bind ffmpeg_location in yt-dlp: {e}")

    return opts

def analyze_media_url(url: str) -> Dict[str, Any]:
    """
    Extracts metadata, stream formats, and audio information without downloading media.
    Catches DRM and access restriction errors gracefully with automatic cookie fallback.
    """
    opts = get_ydl_base_options()
    opts["skip_download"] = True
    opts["check_formats"] = False
    
    def _extract(options: Dict[str, Any]):
        with yt_dlp.YoutubeDL(options) as ydl:
            info = ydl.extract_info(url, download=False)
            if not info:
                raise ExtractorError("No media stream information could be retrieved from this URL.")
            
            # If playlist returned, take first entry
            if "entries" in info:
                entries = list(info.get("entries", []))
                if entries and entries[0]:
                    info = entries[0]
                else:
                    raise ExtractorError("No media entries found.")
            
            return info

    try:
        return _extract(opts)
    except yt_dlp.utils.DownloadError as e:
        err_msg = str(e).lower()
        logger.warning(f"yt-dlp download error for {url}: {err_msg}")
        
        # If proxy failed / expired / exhausted quota (e.g. Tunnel connection failed, 407, 402), retry cleanly directly
        if opts.get("proxy") and any(k in err_msg for k in ["proxy", "tunnel", "unable to connect to proxy", "407", "402", "502", "connection refused"]):
            logger.warning(f"Proxy connection failed for {url} ({err_msg[:80]}); retrying cleanly with direct connection...")
            try:
                opts_noproxy = dict(opts)
                opts_noproxy["proxy"] = ""
                return _extract(opts_noproxy)
            except Exception as retry_err:
                logger.warning(f"Fallback without proxy failed: {retry_err}")
                err_msg = str(retry_err).lower()

        # If cookies triggered a sign-in or bot challenge, retry cleanly without cookies
        if opts.get("cookiefile") and any(k in err_msg for k in ["sign in", "login", "bot", "cookie"]):
            logger.info(f"Cookie challenge detected for {url}; retrying without cookies...")
            try:
                opts_nocookies = dict(opts)
                opts_nocookies.pop("cookiefile", None)
                return _extract(opts_nocookies)
            except Exception as retry_err:
                logger.warning(f"Retry without cookies failed: {retry_err}")
                err_msg = str(retry_err).lower()
        
        # Check for datacenter / bot block patterns
        if "failed to extract any player response" in err_msg or "confirm you're not a bot" in err_msg:
            raise ExtractorError(
                "YouTube anti-bot block on cloud server. "
                "For 100% free unlimited downloads, switch to Local PC Wi-Fi (http://<PC-IP>:8000) or refresh cookies."
            )
        # Check for DRM / restricted patterns
        elif any(keyword in err_msg for keyword in [
            "drm", "protected", "copyright", "private", "members-only", 
            "premium", "paywall", "geographic", "blocked", "restricted"
        ]):
            raise MediaRestrictedError(
                f"Media restricted: {str(e)[:180]}"
            )
        elif "unsupported url" in err_msg or "is not a valid url" in err_msg:
            raise ExtractorError("The provided URL is not a supported media source.")
        elif "video unavailable" in err_msg or "not found" in err_msg:
            raise ExtractorError("The requested media is unavailable or has been removed.")
        else:
            raise ExtractorError(f"Media extraction failed: {str(e)[:120]}")
            
    except Exception as e:
        logger.error(f"Unexpected error analyzing URL {url}: {e}")
        raise ExtractorError(f"Failed to analyze media URL: {str(e)}")

def download_media_stream(
    url: str,
    format_id: str,
    output_template: str,
    progress_callback: Optional[Callable[[Dict[str, Any]], None]] = None
) -> Dict[str, Any]:
    """
    Downloads the specified format stream to disk using yt-dlp with Windows safe paths.
    """
    opts = get_ydl_base_options()
    
    # Bypass proxy for downloading actual media stream bytes to prevent burning limited proxy quotas
    # Google Video CDN links can be streamed directly without consuming proxy bandwidth
    if not os.environ.get("FORCE_PROXY_DOWNLOADS", "").lower() in ("true", "1", "yes"):
        opts["proxy"] = ""

    # Isolate directory and clean normalized output path
    out_path = Path(output_template)
    job_dir = str(out_path.parent.resolve())
    os.makedirs(job_dir, exist_ok=True)
    
    # Use direct absolute normalized path for outtmpl without conflicting paths dictionary
    full_output_tmpl = os.path.normpath(str(out_path))
    opts["outtmpl"] = full_output_tmpl
    opts["nopart"] = True
    
    # Resilient format selector: prioritize requested format_id with safe fallbacks
    if format_id and format_id.strip() and format_id.strip().lower() not in ("none", "null", "undefined"):
        clean_fid = format_id.strip()
        if "/" in clean_fid:
            opts["format"] = f"{clean_fid}/best"
        else:
            opts["format"] = f"{clean_fid}/bestaudio/best/bestvideo+bestaudio"
    else:
        opts["format"] = "bestaudio/best/bestvideo+bestaudio"
    
    if progress_callback:
        opts["progress_hooks"] = [progress_callback]
        
    def _download(options: Dict[str, Any]):
        with yt_dlp.YoutubeDL(options) as ydl:
            return ydl.extract_info(url, download=True)

    try:
        return _download(opts)
    except yt_dlp.utils.DownloadError as e:
        err_msg = str(e).lower()
        # Fallback if download proxy failed
        if opts.get("proxy") and any(k in err_msg for k in ["proxy", "tunnel", "unable to connect to proxy", "407", "402", "502"]):
            logger.warning(f"Download proxy error for {url}; retrying directly without proxy...")
            try:
                opts_noproxy = dict(opts)
                opts_noproxy["proxy"] = ""
                return _download(opts_noproxy)
            except Exception as retry_err:
                logger.warning(f"Download retry without proxy failed: {retry_err}")
                err_msg = str(retry_err).lower()

        if opts.get("cookiefile") and any(k in err_msg for k in ["sign in", "login", "bot", "cookie"]):
            logger.info(f"Download cookie challenge for {url}; retrying without cookies...")
            try:
                opts_nocookies = dict(opts)
                opts_nocookies.pop("cookiefile", None)
                return _download(opts_nocookies)
            except Exception as retry_err:
                logger.warning(f"Download retry without cookies failed: {retry_err}")
                err_msg = str(retry_err).lower()

        # Resilient format fallback retry: if requested format_id was unavailable, retry with best available stream
        try:
            logger.info(f"Retrying download with resilient general stream selector for {url}...")
            opts_fallback = dict(opts)
            opts_fallback["format"] = "best/bestaudio"
            opts_fallback["nopart"] = True
            opts_fallback["outtmpl"] = os.path.normpath(os.path.join(job_dir, "source_media.%(ext)s"))
            return _download(opts_fallback)
        except Exception as fallback_err:
            logger.warning(f"Resilient stream fallback also failed: {fallback_err}")
                
        if "failed to extract any player response" in err_msg or "confirm you're not a bot" in err_msg:
            raise ExtractorError(
                "YouTube anti-bot block detected on this server IP. "
                "Connect your mobile app to your Local PC server (http://<PC-IP>:8000) on the same Wi-Fi."
            )
        if any(keyword in err_msg for keyword in ["drm", "protected", "private"]):
            raise MediaRestrictedError(
                "This media cannot be processed because it is protected, restricted, or unavailable."
            )
        raise ExtractorError(f"Download failed: {str(e)[:120]}")
    except yt_dlp.utils.UnavailableVideoError as e:
        err_str = str(e)
        logger.warning(f"UnavailableVideoError for {url}: {err_str}; attempting safe fallback stream...")
        try:
            opts_fallback = dict(opts)
            opts_fallback["format"] = "best"
            opts_fallback["nopart"] = True
            opts_fallback["outtmpl"] = os.path.normpath(os.path.join(job_dir, "source_media.%(ext)s"))
            return _download(opts_fallback)
        except Exception as retry_err:
            logger.error(f"Fallback after UnavailableVideoError failed: {retry_err}")
            if "errno 22" in str(retry_err).lower() or "errno 22" in err_str.lower():
                raise ExtractorError("Storage write error: unable to write media stream parameters to disk.")
            raise ExtractorError(f"Media stream unavailable: {err_str[:120]}")
    except yt_dlp.utils.YoutubeDLError as e:
        logger.error(f"YoutubeDLError downloading {url}: {e}")
        raise ExtractorError(f"Stream download error: {str(e)[:120]}")
    except Exception as e:
        err_str = str(e)
        logger.error(f"Unexpected error downloading stream: {err_str}")
        try:
            opts_fallback = dict(opts)
            opts_fallback["format"] = "best"
            opts_fallback["nopart"] = True
            opts_fallback["outtmpl"] = os.path.normpath(os.path.join(job_dir, "source_media.%(ext)s"))
            return _download(opts_fallback)
        except Exception:
            pass
        if "errno 22" in err_str.lower():
            raise ExtractorError("Storage write error: invalid file argument or path restriction.")
        raise ExtractorError(f"Stream download encountered an error: {err_str[:120]}")
